project:
  type: website
  render:
    - index.qmd
    - activities.qmd
    - as_209.qmd
    - hd_163296.qmd
    - hl_tau.qmd
    - im_lup.qmd
    - pds_70.qmd

website:
  title: "Pilot Protoplanetary Disk Catalog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: activities.qmd
        text: Activities

format:
  html:
    theme: darkly
    css: styles.css
    toc: true
    page-layout: full

resources:
  - data/**
  - images/**