<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>AS 209: disco protoplanetario – Catálogo piloto de discos protoplanetarios</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-94b323657c735dfe3b1bf6ebb2c33a55.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Catálogo piloto de discos protoplanetarios</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./activity_morphology_es.html"> 
<span class="menu-text">Actividad morfológica</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./simulation.html"> 
<span class="menu-text">Simulación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./investigaciones_publicaciones.html"> 
<span class="menu-text">Investigaciones y publicaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./sobre_el_proyecto.html"> 
<span class="menu-text">Sobre el proyecto</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#nombres-del-objeto" id="toc-nombres-del-objeto" class="nav-link active" data-scroll-target="#nombres-del-objeto">Nombres del objeto</a></li>
  <li><a href="#ubicación" id="toc-ubicación" class="nav-link" data-scroll-target="#ubicación">Ubicación</a></li>
  <li><a href="#descripción-general-del-sistema" id="toc-descripción-general-del-sistema" class="nav-link" data-scroll-target="#descripción-general-del-sistema">Descripción general del sistema</a></li>
  <li><a href="#propiedades-generales-del-sistema" id="toc-propiedades-generales-del-sistema" class="nav-link" data-scroll-target="#propiedades-generales-del-sistema">Propiedades generales del sistema</a></li>
  <li><a href="#morfología-del-disco" id="toc-morfología-del-disco" class="nav-link" data-scroll-target="#morfología-del-disco">Morfología del disco</a></li>
  <li><a href="#mediciones-morfológicas" id="toc-mediciones-morfológicas" class="nav-link" data-scroll-target="#mediciones-morfológicas">Mediciones morfológicas</a></li>
  <li><a href="#polvo-en-el-disco" id="toc-polvo-en-el-disco" class="nav-link" data-scroll-target="#polvo-en-el-disco">Polvo en el disco</a></li>
  <li><a href="#propiedades-del-polvo" id="toc-propiedades-del-polvo" class="nav-link" data-scroll-target="#propiedades-del-polvo">Propiedades del polvo</a></li>
  <li><a href="#gas-en-el-disco" id="toc-gas-en-el-disco" class="nav-link" data-scroll-target="#gas-en-el-disco">Gas en el disco</a></li>
  <li><a href="#propiedades-del-gas" id="toc-propiedades-del-gas" class="nav-link" data-scroll-target="#propiedades-del-gas">Propiedades del gas</a></li>
  <li><a href="#evidencia-de-formación-planetaria" id="toc-evidencia-de-formación-planetaria" class="nav-link" data-scroll-target="#evidencia-de-formación-planetaria">Evidencia de formación planetaria</a></li>
  <li><a href="#interpretación-física-de-as-209" id="toc-interpretación-física-de-as-209" class="nav-link" data-scroll-target="#interpretación-física-de-as-209">Interpretación física de AS 209</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">AS 209: disco protoplanetario</h1>
</div>



<div class="quarto-title-meta column-page-left">

    
  
    
  </div>
  


</header>


<div id="fig-as209" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-as209-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/as_209_ficha.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Imagen de ALMA del disco protoplanetario alrededor de AS 209, donde se observan múltiples anillos estrechos y brechas que podrían indicar formación planetaria en curso. Crédito: ALMA (ESO/NAOJ/NRAO); A. Sierra (U. Chile)."><img src="images/as_209_ficha.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="650"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-as209-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Imagen de ALMA del disco protoplanetario alrededor de AS 209, donde se observan múltiples anillos estrechos y brechas que podrían indicar formación planetaria en curso. Crédito: ALMA (ESO/NAOJ/NRAO); A. Sierra (U. Chile).
</figcaption>
</figure>
</div>
<p>Como se muestra en la <a href="#fig-as209" class="quarto-xref">Figure&nbsp;1</a>, el disco de AS 209 presenta una secuencia de anillos brillantes y brechas oscuras en la emisión continua del polvo.</p>
<section id="nombres-del-objeto" class="level2">
<h2 class="anchored" data-anchor-id="nombres-del-objeto">Nombres del objeto</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Catálogo</th>
<th>Nombre</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nombre principal</td>
<td>AS 209</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Otras designaciones</td>
<td>PDS 92; V1121 Oph; HBC 270; IRAS 16464-1416</td>
<td><span class="citation" data-cites="gregorio-hetem1992iras">(<a href="#ref-gregorio-hetem1992iras" role="doc-biblioref">Gregorio-Hetem et al. 1992</a>)</span></td>
</tr>
<tr class="odd">
<td>Ubicación</td>
<td>Región de formación estelar de Ofiuco</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="ubicación" class="level2">
<h2 class="anchored" data-anchor-id="ubicación">Ubicación</h2>
<p>AS 209 se encuentra en la <strong>nube molecular de Ofiuco</strong>, una región cercana de formación estelar que alberga numerosos sistemas jóvenes. En la literatura, la fuente se describe como una <strong>estrella T Tauri</strong> ubicada en la joven región de formación estelar de Ofiuco, a una distancia de <strong>126 pc</strong> del Sol <span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span>.</p>
<p>Su cercanía convierte a AS 209 en un objetivo excelente para observaciones milimétricas de alta resolución, ya que permite estudiar con detalle tanto las subestructuras del polvo como las del gas.</p>
</section>
<section id="descripción-general-del-sistema" class="level2">
<h2 class="anchored" data-anchor-id="descripción-general-del-sistema">Descripción general del sistema</h2>
<p>AS 209 es un sistema protoplanetario joven alrededor de una estrella T Tauri, con tipo espectral <strong>K5</strong>, masa estelar de aproximadamente <strong>0.83–0.9 M☉</strong> y luminosidad de <strong>1.5 L☉</strong> <span class="citation" data-cites="tazzari2016 fedele2018 zhang2018">(<a href="#ref-tazzari2016" role="doc-biblioref">Tazzari et al. 2016</a>; <a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>; <a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span>. Se encuentra en la región de formación estelar de Ofiuco, a una distancia de <strong>126 pc</strong> <span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span>.</p>
<p>En el continuo a <strong>1.3 mm</strong>, Fedele et al.&nbsp;muestran que su disco presenta un núcleo central brillante, dos anillos prominentes alrededor de <strong>~75 au</strong> y <strong>~130 au</strong>, y dos brechas alrededor de <strong>~62 au</strong> y <strong>~103 au</strong>. La brecha interna es más estrecha y menos profunda que la externa <span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span>.</p>
<p>Sobre esta base observacional, Zhang et al.&nbsp;destacan la buena concordancia entre observaciones y simulaciones para AS 209, describiéndolo como un sistema con muchas brechas. Esto refuerza la idea de que AS 209 es un objeto especialmente valioso para estudiar subestructuras de disco y su posible conexión con la formación planetaria <span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span>.</p>
<p>Además, el análisis multi-longitud de onda de Tazzari et al.&nbsp;muestra evidencia de evolución radial del polvo: los granos más grandes se concentran en las regiones internas, mientras que los granos más pequeños dominan el disco externo <span class="citation" data-cites="tazzari2016">(<a href="#ref-tazzari2016" role="doc-biblioref">Tazzari et al. 2016</a>)</span>. Esto sugiere que el crecimiento y la redistribución de sólidos no ocurren de forma uniforme en todo el disco.</p>
</section>
<section id="propiedades-generales-del-sistema" class="level2">
<h2 class="anchored" data-anchor-id="propiedades-generales-del-sistema">Propiedades generales del sistema</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Propiedad</th>
<th>Valor</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Distancia</td>
<td>126 pc</td>
<td>Distancia desde el Sol hasta AS 209.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Edad</td>
<td>~0.5–1.0 Myr</td>
<td>Edad estimada del sistema.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Tipo espectral</td>
<td>K5</td>
<td>Clase espectral de la estrella central.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Temperatura estelar</td>
<td>4250 K</td>
<td>Temperatura efectiva de la estrella.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Masa estelar</td>
<td>0.83–0.9 M☉</td>
<td>Masa de la estrella central.</td>
<td><span class="citation" data-cites="zhang2018 fedele2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>; <a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Luminosidad estelar</td>
<td>1.5 L☉</td>
<td>Luminosidad de la estrella central.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Radio del disco de polvo</td>
<td>~170–180 au</td>
<td>Extensión externa de la emisión continua del polvo.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Radio externo del gas</td>
<td>&gt;200 au</td>
<td>Extensión externa del disco trazado por emisión de CO.</td>
<td><span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span></td>
</tr>
<tr class="odd">
<td>Inclinación del disco</td>
<td>35.3 ± 0.8°</td>
<td>Inclinación del disco respecto de la línea de visión.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="morfología-del-disco" class="level2">
<h2 class="anchored" data-anchor-id="morfología-del-disco">Morfología del disco</h2>
<p>AS 209 presenta una arquitectura radial con múltiples brechas. Zhang et al.&nbsp;señalan que estudios previos identificaron varios anillos oscuros en este sistema, ubicados aproximadamente a <strong>9, 24, 35, 61, 90, 105 y 137 au</strong> <span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span>. Estas subestructuras no tienen todas la misma profundidad, sino que varían dependiendo de su ubicación dentro del disco.</p>
<p>Por ejemplo, la brecha alrededor de <strong>61 au</strong> es menos profunda que la brecha principal y se ubica a una distancia que permite interpretarla como una brecha secundaria inducida por un planeta <span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span>. En otras palabras, esta brecha sería menos marcada que la brecha principal cercana a <strong>100 au</strong>.</p>
<p>Dentro de ese mismo marco interpretativo, Zhang et al.&nbsp;muestran que una simulación con un planeta ubicado a <strong>99 au</strong> puede reproducir no solo la brecha principal alrededor de <strong>100 au</strong>, sino también la posición y amplitud de brechas internas secundarias, terciarias e incluso una cuarta brecha a <strong>61, 35 y 24 au</strong> <span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span>.</p>
<p>Esta morfología también se observa claramente en el continuo de polvo presentado por Fedele et al.&nbsp;En esas observaciones, la emisión continua está caracterizada por un núcleo central brillante y dos anillos de polvo más débiles que alcanzan su máximo cerca de <strong>~75 au</strong> y <strong>~130 au</strong>, separados por dos brechas a <strong>~62 au</strong> y <strong>~103 au</strong> <span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span>.</p>
<p>En general, la distribución de brillo a <strong>1.3 mm</strong> de AS 209 puede describirse mediante un perfil con dos brechas profundas y un anillo externo de exceso de emisión alrededor de <strong>~130 au</strong> <span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span>. Por lo tanto, el disco no es una estructura continua y lisa, sino un sistema con anillos y brechas radiales bien definidos.</p>
</section>
<section id="mediciones-morfológicas" class="level2">
<h2 class="anchored" data-anchor-id="mediciones-morfológicas">Mediciones morfológicas</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Estructura</th>
<th>Medición</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>D9</td>
<td>9 au</td>
<td>Brecha de polvo interna identificada en el disco de AS 209.</td>
<td><span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>D24</td>
<td>24 au</td>
<td>Brecha interna de polvo; interpretada como una cuarta brecha interna en el escenario de un solo planeta.</td>
<td><span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>D35</td>
<td>35 au</td>
<td>Brecha interna de polvo; interpretada como una brecha terciaria en el escenario de un solo planeta.</td>
<td><span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>D61</td>
<td>61 au</td>
<td>Brecha secundaria de polvo; menos profunda que la brecha principal.</td>
<td><span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>D62</td>
<td>61.7 ± 0.5 au</td>
<td>Brecha interna principal identificada en el continuo a 1.3 mm.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>B75</td>
<td>~75 au</td>
<td>Anillo interno de polvo donde la emisión continua alcanza un máximo.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>D90</td>
<td>90 au</td>
<td>Brecha de polvo identificada en el disco externo.</td>
<td><span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>D105</td>
<td>105 au</td>
<td>Brecha de polvo asociada con la región de la brecha externa principal.</td>
<td><span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>D103</td>
<td>103.2 ± 0.4 au</td>
<td>Brecha externa principal identificada en el continuo a 1.3 mm.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>B130</td>
<td>~130 au</td>
<td>Anillo externo de polvo donde la emisión continua alcanza un máximo.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>D137</td>
<td>137 au</td>
<td>Brecha externa de polvo en la región más alejada del disco.</td>
<td><span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="polvo-en-el-disco" class="level2">
<h2 class="anchored" data-anchor-id="polvo-en-el-disco">Polvo en el disco</h2>
<p>El estudio del polvo en discos protoplanetarios se apoya en observaciones de alta resolución angular a longitudes de onda submilimétricas y milimétricas, ya que estas permiten rastrear la distribución radial de los granos sólidos <span class="citation" data-cites="tazzari2016">(<a href="#ref-tazzari2016" role="doc-biblioref">Tazzari et al. 2016</a>)</span>.</p>
<p>En AS 209, el polvo no se distribuye de manera uniforme. El análisis multi-longitud de onda muestra que el tamaño máximo de grano disminuye con el radio: en el disco interno, entre <strong>15 y 30 au</strong>, se infieren granos grandes de hasta aproximadamente <strong>1 cm</strong>, mientras que en el disco externo, a radios mayores que <strong>~80 au</strong>, predominan granos más pequeños, de tamaño cercano a <strong>1 mm</strong> <span class="citation" data-cites="tazzari2016">(<a href="#ref-tazzari2016" role="doc-biblioref">Tazzari et al. 2016</a>)</span>.</p>
<p>Esta variación radial indica que el crecimiento y la evolución del polvo dependen de las condiciones locales del disco. Los granos grandes tienden a concentrarse en regiones internas, mientras que el material de menor tamaño domina las zonas externas.</p>
<p>Fedele et al.&nbsp;muestran además que la depleción de polvo no es igual en todas las brechas. La brecha interna se encuentra parcialmente rellena por granos milimétricos, mientras que la brecha externa está mucho más vacía de polvo <span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span>. Esto indica que las subestructuras del disco afectan de manera distinta a los sólidos dependiendo de su ubicación.</p>
<p>Un proceso clave para interpretar esta distribución es la deriva radial. En principio, la deriva radial tendería a remover rápidamente los granos grandes del disco en escalas menores a 1 Myr, a menos que existan mecanismos capaces de detener o ralentizar su migración <span class="citation" data-cites="tazzari2016">(<a href="#ref-tazzari2016" role="doc-biblioref">Tazzari et al. 2016</a>)</span>. En AS 209, los anillos pueden actuar como <strong>trampas de polvo</strong>, donde la migración radial hacia el interior se reduce o se detiene <span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span>.</p>
<p>Estas trampas ofrecen un ambiente favorable para que el polvo crezca localmente y se acumule. En este escenario, un planeta podría abrir una brecha y producir una acumulación de polvo en el borde externo de su órbita <span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span>.</p>
</section>
<section id="propiedades-del-polvo" class="level2">
<h2 class="anchored" data-anchor-id="propiedades-del-polvo">Propiedades del polvo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Propiedad</th>
<th>Valor</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Extensión externa del continuo de polvo</td>
<td>~170–180 au</td>
<td>Extensión radial externa de la emisión tenue del continuo de polvo.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Masa de polvo</td>
<td>3.5 × 10^-4 M☉</td>
<td>Masa de polvo fiducial adoptada para reproducir la estructura observada del polvo.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Tamaño máximo de grano</td>
<td>2000 μm</td>
<td>Tamaño máximo de grano adoptado para la población de polvo grande en el modelo de AS 209.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Factor de depleción del gap interno</td>
<td>~0.03</td>
<td>Factor de reducción de brillo del gap interno en el mejor ajuste.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Factor de depleción del gap externo</td>
<td>~0.025</td>
<td>Factor de reducción de brillo del gap externo en el mejor ajuste.</td>
<td><span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Densidad superficial de polvo</td>
<td>0.17 g cm^-2</td>
<td>Cantidad promedio de polvo por unidad de área en el disco externo, alrededor del gap principal.</td>
<td><span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="gas-en-el-disco" class="level2">
<h2 class="anchored" data-anchor-id="gas-en-el-disco">Gas en el disco</h2>
<p>En AS 209, el gas tampoco se distribuye uniformemente, y su estructura se vuelve más clara cuando se analizan distintos trazadores moleculares en conjunto.</p>
<p>La emisión de C<span class="math inline">\(^{18}\)</span>O revela una organización radial bien definida, con una concentración interna de gas cerca de la estrella y un anillo externo alrededor de <strong>140 au</strong>, separados por una región de emisión más débil <span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span>. Además, su perfil radial presenta una caída de intensidad entre las dos brechas del continuo, lo que sugiere que las subestructuras observadas en el polvo también tienen una contraparte en el gas <span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span>.</p>
<p>Esta conexión se refuerza con Fedele et al., quienes señalan que la emisión extendida de C<span class="math inline">\(^{18}\)</span>O alcanza un máximo cerca de <strong>130 au</strong>, en una región coespacial con el anillo externo de polvo <span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span>. Esto indica que el anillo externo de polvo también tiene una contraparte gaseosa.</p>
<p>Además, esa emisión a gran escala de C<span class="math inline">\(^{18}\)</span>O parece seguir la densidad superficial real del gas en el disco externo y apunta a una caída de densidad de gas por un factor de algunos dentro de la brecha externa <strong>D103</strong> <span class="citation" data-cites="fedele2018">(<a href="#ref-fedele2018" role="doc-biblioref">Fedele et al. 2018</a>)</span>. Por lo tanto, la brecha externa no es solo una subestructura del polvo, sino también una región donde disminuye la densidad del gas.</p>
<p>En contraste, DCO<span class="math inline">\(^+\)</span> no sigue exactamente el mismo patrón que C<span class="math inline">\(^{18}\)</span>O. Favre et al.&nbsp;reportan dos anillos de DCO<span class="math inline">\(^+\)</span>: uno ubicado entre las dos brechas principales de polvo y otro más allá de la brecha externa <span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span>. Esto muestra que distintos trazadores revelan distintas condiciones físicas y químicas dentro del disco.</p>
<p>Para explicar la morfología observada, Favre et al.&nbsp;concluyen que la densidad superficial del gas debe disminuir dentro de las brechas <span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span>. Esto significa que los efectos de temperatura u opacidad por sí solos no son suficientes: se requiere una disminución real en la densidad superficial del gas.</p>
<p>En conjunto, esta evidencia apoya una interpretación dinámica del disco, donde la estructura gaseosa de AS 209 habría sido modificada por una perturbación del gas producida por uno o más planetas en formación <span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span>.</p>
</section>
<section id="propiedades-del-gas" class="level2">
<h2 class="anchored" data-anchor-id="propiedades-del-gas">Propiedades del gas</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Propiedad</th>
<th>Valor</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Extensión externa de CO</td>
<td>&gt;200 au</td>
<td>El gas trazado por CO se extiende más lejos que el disco de polvo milimétrico.</td>
<td><span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span></td>
</tr>
<tr class="even">
<td>Emisión interna de C<span class="math inline">\(^{18}\)</span>O</td>
<td>≤60 au</td>
<td>Concentración interna de gas cerca de la estrella, trazada por C<span class="math inline">\(^{18}\)</span>O.</td>
<td><span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span></td>
</tr>
<tr class="odd">
<td>Anillo externo de C<span class="math inline">\(^{18}\)</span>O</td>
<td>140 au</td>
<td>Anillo gaseoso externo detectado en emisión de C<span class="math inline">\(^{18}\)</span>O.</td>
<td><span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span></td>
</tr>
<tr class="even">
<td>Anillo interno de DCO<span class="math inline">\(^+\)</span></td>
<td>66–95 au</td>
<td>Anillo gaseoso ubicado entre las dos brechas principales de polvo.</td>
<td><span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span></td>
</tr>
<tr class="odd">
<td>Anillo externo de DCO<span class="math inline">\(^+\)</span></td>
<td>&gt;120 au</td>
<td>Anillo gaseoso externo detectado más allá de la brecha externa de polvo.</td>
<td><span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span></td>
</tr>
<tr class="even">
<td>Profundidad óptica de C<span class="math inline">\(^{18}\)</span>O</td>
<td>≤0.8</td>
<td>C<span class="math inline">\(^{18}\)</span>O es ópticamente delgado, por lo que traza de manera más directa la estructura del gas.</td>
<td><span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span></td>
</tr>
<tr class="odd">
<td>Profundidad óptica de CO y <span class="math inline">\(^{13}\)</span>CO</td>
<td>≥2.5</td>
<td>CO y <span class="math inline">\(^{13}\)</span>CO son ópticamente gruesos, por lo que pueden ocultar parte de la estructura del gas.</td>
<td><span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="evidencia-de-formación-planetaria" class="level2">
<h2 class="anchored" data-anchor-id="evidencia-de-formación-planetaria">Evidencia de formación planetaria</h2>
<p>En AS 209, la evidencia de formación planetaria no depende de una única subestructura aislada, sino de la forma consistente en que observaciones y modelos describen el disco como un sistema dinámicamente perturbado.</p>
<p>En el continuo milimétrico, ya se había propuesto que los anillos y brechas observados a <strong>1.3 mm</strong> probablemente se deben a la formación de planetas, en concordancia con simulaciones hidrodinámicas <span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span>. Esto significa que la arquitectura anillada del disco es compatible con la acción de planetas en formación.</p>
<p>Esta interpretación se fortalece con los resultados de Zhang et al.&nbsp;Una simulación con un planeta ubicado a <strong>99 au</strong> no solo reproduce la brecha principal alrededor de <strong>100 au</strong>, sino también la posición y amplitud de varias brechas internas, incluyendo las de <strong>61, 35 y 24 au</strong> <span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span>. En otras palabras, un solo planeta embebido podría explicar tanto la brecha principal como varias subestructuras internas.</p>
<p>Por esta razón, Zhang et al.&nbsp;concluyen que AS 209 es uno de los casos más plausibles donde realmente podría existir un planeta dentro de la brecha de <strong>~100 au</strong> <span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span>.</p>
<p>La evidencia no proviene solo del polvo. Favre et al.&nbsp;concluyen que las brechas de polvo observadas probablemente se deben a una perturbación de la densidad superficial del gas inducida por un planeta en formación de al menos <strong>0.2 M_J</strong> <span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span>. Esto refuerza la idea de que las brechas no son simples variaciones aparentes de brillo, sino el resultado de un proceso real de interacción planeta-disco.</p>
</section>
<section id="interpretación-física-de-as-209" class="level2">
<h2 class="anchored" data-anchor-id="interpretación-física-de-as-209">Interpretación física de AS 209</h2>
<p>AS 209 puede entenderse como un disco joven donde la evolución del polvo y la interacción planeta-disco actúan de manera conjunta.</p>
<p>Por un lado, el polvo no evoluciona uniformemente en todo el sistema. Los granos más grandes se concentran hacia las regiones internas, mientras que los granos más pequeños dominan en zonas más externas. Este patrón es consistente con crecimiento de granos, deriva radial y la necesidad de mecanismos de retención que eviten que los sólidos se pierdan rápidamente hacia la estrella <span class="citation" data-cites="tazzari2016">(<a href="#ref-tazzari2016" role="doc-biblioref">Tazzari et al. 2016</a>)</span>.</p>
<p>Por otro lado, la arquitectura de anillos y brechas se explica mejor si el disco está siendo esculpido dinámicamente por un planeta embebido en un ambiente de muy baja viscosidad. Zhang et al.&nbsp;muestran que un planeta con (q = 10^{-4}), en un disco con (= 10^{-5}) y (h/r = 0.05), puede explicar cinco brechas ubicadas a <strong>24, 35, 62, 90 y 105 au</strong> <span class="citation" data-cites="zhang2018">(<a href="#ref-zhang2018" role="doc-biblioref">Zhang et al. 2018</a>)</span>. Esto implica que un único planeta externo podría explicar gran parte de la estructura radial del sistema.</p>
<p>Esta interpretación es aún más fuerte porque el gas también se encuentra genuinamente perturbado. Favre et al.&nbsp;concluyen que las brechas de polvo observadas probablemente se deben a una perturbación en la densidad superficial del gas inducida por un planeta de al menos <strong>0.2 M_J</strong> en formación <span class="citation" data-cites="favre2019">(<a href="#ref-favre2019" role="doc-biblioref">Favre et al. 2019</a>)</span>. Esto indica que las brechas no son solo variaciones de brillo en el polvo, sino señales de una reorganización real de la densidad superficial del disco.</p>
<p>En conjunto, AS 209 se interpreta mejor como un disco de baja turbulencia en el que un planeta en formación ya estaría remodelando tanto el polvo como el gas, dejando una huella observable de formación planetaria en curso.</p>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">Referencias</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-favre2019" class="csl-entry" role="listitem">
Favre, Cécile, Davide Fedele, Luke Maud, et al. 2019. <span>“Gas Density Perturbations Induced by One or More Forming Planets in the AS 209 Protoplanetary Disk as Seen with ALMA.”</span> <em>The Astrophysical Journal</em> 871: 107. <a href="https://doi.org/10.3847/1538-4357/aaf80c">https://doi.org/10.3847/1538-4357/aaf80c</a>.
</div>
<div id="ref-fedele2018" class="csl-entry" role="listitem">
Fedele, Davide, Marco Tazzari, Richard Booth, et al. 2018. <span>“ALMA Continuum Observations of the Protoplanetary Disk AS 209: Evidence of Multiple Gaps Opened by a Single Planet?”</span> <em>Astronomy &amp; Astrophysics</em> 610: A24. <a href="https://doi.org/10.1051/0004-6361/201731978">https://doi.org/10.1051/0004-6361/201731978</a>.
</div>
<div id="ref-gregorio-hetem1992iras" class="csl-entry" role="listitem">
Gregorio-Hetem, J., J. R. D. Lepine, G. R. Quast, C. A. O. Torres, and R. de La Reza. 1992. <span>“A Search for t Tauri Stars Based on the IRAS Point Source Catalog. i.”</span> <em>Astronomical Journal</em> 103 (February): 549–63. <a href="https://doi.org/10.1086/116082">https://doi.org/10.1086/116082</a>.
</div>
<div id="ref-tazzari2016" class="csl-entry" role="listitem">
Tazzari, M., L. Testi, B. Ercolano, et al. 2016. <span>“Multiwavelength Analysis for Interferometric (Sub-)mm Observations of Protoplanetary Disks: Radial Constraints on the Dust Properties and the Disk Structure.”</span> <em>Astronomy &amp; Astrophysics</em> 588: A53. <a href="https://doi.org/10.1051/0004-6361/201527423">https://doi.org/10.1051/0004-6361/201527423</a>.
</div>
<div id="ref-zhang2018" class="csl-entry" role="listitem">
Zhang, Shangjia, Zhaohuan Zhu, Jane Huang, et al. 2018. <span>“The Disk Substructures at High Angular Resolution Project (DSHARP). VII. The Planet–Disk Interactions Interpretation.”</span> <em>The Astrophysical Journal Letters</em> 869: L47. <a href="https://doi.org/10.3847/2041-8213/aaf744">https://doi.org/10.3847/2041-8213/aaf744</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/martinaAbarca\.github\.io\/pilot-protoplanetary-disks-catalog\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>