<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>HD 163296: disco protoplanetario – Catálogo piloto de discos protoplanetarios</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-94b323657c735dfe3b1bf6ebb2c33a55.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Catálogo piloto de discos protoplanetarios</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./activity_morphology_es.html"> 
<span class="menu-text">Actividad morfológica</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./simulation.html"> 
<span class="menu-text">Simulación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./investigaciones_publicaciones.html"> 
<span class="menu-text">Investigaciones y publicaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./sobre_el_proyecto.html"> 
<span class="menu-text">Sobre el proyecto</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#nombres-del-objeto" id="toc-nombres-del-objeto" class="nav-link active" data-scroll-target="#nombres-del-objeto">Nombres del objeto</a></li>
  <li><a href="#ubicación" id="toc-ubicación" class="nav-link" data-scroll-target="#ubicación">Ubicación</a></li>
  <li><a href="#descripción-general-del-sistema" id="toc-descripción-general-del-sistema" class="nav-link" data-scroll-target="#descripción-general-del-sistema">Descripción general del sistema</a></li>
  <li><a href="#propiedades-generales-del-sistema" id="toc-propiedades-generales-del-sistema" class="nav-link" data-scroll-target="#propiedades-generales-del-sistema">Propiedades generales del sistema</a></li>
  <li><a href="#morfología-del-disco" id="toc-morfología-del-disco" class="nav-link" data-scroll-target="#morfología-del-disco">Morfología del disco</a></li>
  <li><a href="#mediciones-morfológicas" id="toc-mediciones-morfológicas" class="nav-link" data-scroll-target="#mediciones-morfológicas">Mediciones morfológicas</a></li>
  <li><a href="#polvo-en-el-disco" id="toc-polvo-en-el-disco" class="nav-link" data-scroll-target="#polvo-en-el-disco">Polvo en el disco</a></li>
  <li><a href="#propiedades-del-polvo" id="toc-propiedades-del-polvo" class="nav-link" data-scroll-target="#propiedades-del-polvo">Propiedades del polvo</a></li>
  <li><a href="#gas-en-el-disco" id="toc-gas-en-el-disco" class="nav-link" data-scroll-target="#gas-en-el-disco">Gas en el disco</a></li>
  <li><a href="#propiedades-del-gas" id="toc-propiedades-del-gas" class="nav-link" data-scroll-target="#propiedades-del-gas">Propiedades del gas</a></li>
  <li><a href="#evidencia-de-formación-planetaria" id="toc-evidencia-de-formación-planetaria" class="nav-link" data-scroll-target="#evidencia-de-formación-planetaria">Evidencia de formación planetaria</a></li>
  <li><a href="#interpretación-física-de-hd-163296" id="toc-interpretación-física-de-hd-163296" class="nav-link" data-scroll-target="#interpretación-física-de-hd-163296">Interpretación física de HD 163296</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HD 163296: disco protoplanetario</h1>
</div>



<div class="quarto-title-meta column-page-left">

    
  
    
  </div>
  


</header>


<div id="fig-hd163296" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hd163296-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/hd_163296_ficha.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Imagen de ALMA del disco protoplanetario alrededor de HD 163296, donde se observan subestructuras prominentes de anillos y brechas en el continuo de polvo. El disco presenta varios anillos y brechas de polvo asociados con estructuras de presión en el material del disco. Crédito de imagen: ALMA (ESO/NAOJ/NRAO)."><img src="images/hd_163296_ficha.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="650"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hd163296-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Imagen de ALMA del disco protoplanetario alrededor de HD 163296, donde se observan subestructuras prominentes de anillos y brechas en el continuo de polvo. El disco presenta varios anillos y brechas de polvo asociados con estructuras de presión en el material del disco. Crédito de imagen: ALMA (ESO/NAOJ/NRAO).
</figcaption>
</figure>
</div>
<p>Como se muestra en la <a href="#fig-hd163296" class="quarto-xref">Figure&nbsp;1</a>, el disco de HD 163296 presenta múltiples brechas oscuras y anillos brillantes en la emisión continua del polvo milimétrico.</p>
<section id="nombres-del-objeto" class="level2">
<h2 class="anchored" data-anchor-id="nombres-del-objeto">Nombres del objeto</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Catálogo</th>
<th>Nombre</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nombre principal</td>
<td>HD 163296</td>
<td><span class="citation" data-cites="isella2016">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Otras designaciones</td>
<td>MWC 275</td>
<td><span class="citation" data-cites="benisty2010">(<a href="#ref-benisty2010" role="doc-biblioref">Benisty et al. 2010</a>)</span></td>
</tr>
<tr class="odd">
<td>Ubicación</td>
<td>No especificada en estos artículos</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="ubicación" class="level2">
<h2 class="anchored" data-anchor-id="ubicación">Ubicación</h2>
<p>HD 163296 es una estrella joven de tipo <strong>Herbig Ae</strong>, ubicada a una distancia aproximada de <strong>101–122 parsecs</strong>, equivalente a unos <strong>330–400 años luz</strong> de la Tierra <span class="citation" data-cites="isella2016 rab2020">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>; <a href="#ref-rab2020" role="doc-biblioref">Rab et al. 2020</a>)</span>.</p>
<p>La estrella pertenece a la clase de objetos de pre-secuencia principal de masa intermedia y está rodeada por uno de los discos protoplanetarios más estudiados. Debido a que el disco es grande, brillante y relativamente aislado, constituye un laboratorio ideal para investigar los procesos físicos que moldean los discos donde se forman planetas.</p>
</section>
<section id="descripción-general-del-sistema" class="level2">
<h2 class="anchored" data-anchor-id="descripción-general-del-sistema">Descripción general del sistema</h2>
<p>HD 163296 es un disco protoplanetario alrededor de una estrella Herbig Ae, cuya morfología de polvo lo ha convertido en un sistema de referencia para estudiar subestructuras radiales. El sistema combina un disco gaseoso grande y dinámicamente ordenado, en rotación kepleriana, con un componente sólido más compacto. En observaciones milimétricas, la emisión del polvo se encuentra confinada dentro de aproximadamente <strong>250 au</strong>, mientras que el gas se extiende mucho más lejos <span class="citation" data-cites="isella2016 diep2019">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>; <a href="#ref-diep2019" role="doc-biblioref">Diep et al. 2019</a>)</span>.</p>
<p>Observaciones anteriores resolvieron tres pares concéntricos de brecha-anillo, con brechas alrededor de <strong>54, 100 y 160 au</strong> <span class="citation" data-cites="diep2019">(<a href="#ref-diep2019" role="doc-biblioref">Diep et al. 2019</a>)</span>. Posteriormente, observaciones de mayor resolución mostraron que esta arquitectura es todavía más rica: además de los anillos y brechas principales, se identificaron un gap oscuro cerca de <strong>10 au</strong>, un anillo brillante alrededor de <strong>15 au</strong>, un crescent o concentración asimétrica de polvo cerca de <strong>55 au</strong>, y varias asimetrías azimutales más débiles <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>En este sentido, la distribución de polvo de HD 163296 no es uniforme ni perfectamente axisimétrica. Presenta variaciones radiales y azimutales que sugieren una redistribución activa del material sólido. Estas estructuras apoyan la hipótesis de que la compleja arquitectura del disco podría estar siendo moldeada por interacción gravitacional con planetas aún no observados directamente <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
</section>
<section id="propiedades-generales-del-sistema" class="level2">
<h2 class="anchored" data-anchor-id="propiedades-generales-del-sistema">Propiedades generales del sistema</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Propiedad</th>
<th>Valor</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Distancia</td>
<td>101 ± 2 pc</td>
<td>Distancia desde la Tierra al sistema HD 163296.</td>
<td><span class="citation" data-cites="pinte2020_dsharp">(<a href="#ref-pinte2020_dsharp" role="doc-biblioref">Pinte et al. 2020</a>)</span></td>
</tr>
<tr class="even">
<td>Clase evolutiva</td>
<td>Herbig Ae</td>
<td>Clasificación evolutiva de la estrella central.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Masa estelar</td>
<td>2.04 M☉</td>
<td>Masa adoptada para la estrella central en el análisis cinemático.</td>
<td><span class="citation" data-cites="pinte2020_dsharp">(<a href="#ref-pinte2020_dsharp" role="doc-biblioref">Pinte et al. 2020</a>)</span></td>
</tr>
<tr class="even">
<td>Tamaño del disco gaseoso</td>
<td>&gt;1000 au de diámetro</td>
<td>Diámetro aproximado completo del disco gaseoso kepleriano extendido.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Extensión de CO</td>
<td>~560 au</td>
<td>Extensión radial de la emisión de CO desde la estrella central.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Inclinación del disco</td>
<td>46.7°</td>
<td>Inclinación usada para interpretar la cinemática del CO.</td>
<td><span class="citation" data-cites="pinte2020_dsharp">(<a href="#ref-pinte2020_dsharp" role="doc-biblioref">Pinte et al. 2020</a>)</span></td>
</tr>
<tr class="odd">
<td>Ángulo de posición</td>
<td>133.3 ± 0.1°</td>
<td>Orientación del eje mayor del disco en el cielo, derivada de los anillos externos de polvo.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Anillos brillantes de polvo</td>
<td>~15, 67, 101 au</td>
<td>Principales anillos brillantes resueltos en el continuo de polvo a 1.25 mm.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Brechas oscuras principales</td>
<td>~10, 45, 86, 141 au</td>
<td>Principales brechas oscuras identificadas en la emisión continua del polvo.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Crescents de polvo</td>
<td>~4 y 55 au</td>
<td>Estructuras asimétricas prominentes observadas en el continuo de polvo.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="morfología-del-disco" class="level2">
<h2 class="anchored" data-anchor-id="morfología-del-disco">Morfología del disco</h2>
<p>La morfología de HD 163296 puede describirse como la de un disco de polvo con una arquitectura jerárquica de anillos y brechas. En el continuo a 1.3 mm, el disco muestra tres pares concéntricos de brecha-anillo y, con mayor resolución, las brechas aparecen más profundas y mejor definidas <span class="citation" data-cites="diep2019">(<a href="#ref-diep2019" role="doc-biblioref">Diep et al. 2019</a>)</span>. Esto permite observar con más claridad la redistribución radial del polvo.</p>
<p>A esta estructura global, Isella et al.&nbsp;(2018) agregan nuevas características morfológicas: una brecha interna oscura cerca de <strong>10 au</strong>, un anillo brillante alrededor de <strong>15 au</strong> y una asimetría azimutal central. En el disco externo, las estructuras <strong>B67, D86, B100, D145 y B155</strong> son bien descritas por círculos concéntricos <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>Sin embargo, el disco no es perfectamente uniforme. El mapa de residuos muestra asimetrías débiles a lo largo de los anillos <strong>B67</strong> y <strong>B100</strong>, mientras que el gap externo y el anillo externo presentan una modulación significativa de su morfología e intensidad <span class="citation" data-cites="isella2018 diep2019">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>; <a href="#ref-diep2019" role="doc-biblioref">Diep et al. 2019</a>)</span>.</p>
<p>En conjunto, HD 163296 presenta una morfología donde coexisten brechas, anillos y asimetrías locales dentro de una estructura globalmente delgada y bien organizada.</p>
</section>
<section id="mediciones-morfológicas" class="level2">
<h2 class="anchored" data-anchor-id="mediciones-morfológicas">Mediciones morfológicas</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Estructura</th>
<th>Medición</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Geometría del disco</td>
<td>Inclinación = 46.7 ± 0.1°; PA = 133.3 ± 0.1°</td>
<td>Geometría media derivada de las estructuras concéntricas externas.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>D10</td>
<td>Radio = 9.96 ± 0.07 au</td>
<td>Brecha oscura interna en el continuo a 1.25 mm; su menor inclinación aparente probablemente está afectada por el suavizado del haz.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>B14</td>
<td>Radio = 14.44 ± 0.07 au mediante ajuste elíptico; 15.5 ± 0.2 au mediante modelo gaussiano; ancho = 8.7 ± 0.2 au</td>
<td>Anillo brillante interno justo fuera de D10; junto con D10, se resuelve principalmente a lo largo del eje mayor del disco.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>D45</td>
<td>Radio = 44.77 ± 0.19 au</td>
<td>Brecha oscura en la región interna del disco externo; su morfología puede estar parcialmente afectada por el crescent de polvo cercano a 55 au.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>B67</td>
<td>Radio = 66.99 ± 0.11 au mediante ajuste elíptico; 67.08 ± 0.03 au mediante modelo gaussiano; ancho = 6.56 ± 0.05 au; asimetría residual = ±0.15 mJy beam⁻¹</td>
<td>Anillo brillante externo; muestra subestructura azimutal real más allá del ruido asociado al haz.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>D86</td>
<td>Radio = 86.61 ± 0.22 au</td>
<td>Brecha oscura entre los dos principales anillos brillantes externos.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>B100</td>
<td>Radio = 99.69 ± 0.08 au mediante ajuste elíptico; 101.16 ± 0.04 au mediante modelo gaussiano; ancho = 5.8 ± 0.1 au; se detectan asimetrías débiles en el mapa de residuos</td>
<td>Segundo anillo brillante externo principal en el continuo de polvo.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>D141</td>
<td>Radio = 140.62 ± 0.96 au</td>
<td>Brecha oscura externa identificada en el mapa de continuo.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>B159</td>
<td>Radio = 158.7 ± 1.2 au</td>
<td>Anillo brillante más externo detectado en el mapa de continuo.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>C4</td>
<td>Radio ≈ 4 au; PA = −44°; intensidad máxima = 0.55 mJy beam⁻¹; extensión azimutal ≈ 180°</td>
<td>Asimetría interna tipo crescent, superpuesta al componente gaussiano más interno del anillo.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>C55</td>
<td>Radio ≈ 55 au; PA = 99°; intensidad máxima = 0.64 mJy beam⁻¹; anchos intrínsecos = 2.2 au radial y 16.9 au azimutal</td>
<td>Crescent de polvo prominente dentro de la región de D45.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="polvo-en-el-disco" class="level2">
<h2 class="anchored" data-anchor-id="polvo-en-el-disco">Polvo en el disco</h2>
<p>En HD 163296, la dinámica del polvo, es decir, la migración radial de sólidos hacia máximos locales de presión del gas, se interpreta como un mecanismo clave para la formación de los anillos. Los anillos brillantes <strong>B67</strong> y <strong>B100</strong> tienen anchos radiales más estrechos que la altura de escala estimada del disco gaseoso, lo que sugiere que el polvo está concentrado y confinado en regiones relativamente angostas <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>Además de los anillos y brechas, el disco también muestra concentraciones asimétricas de polvo. Entre estas destacan estructuras tipo crescent centradas aproximadamente a <strong>4 au</strong> y <strong>55 au</strong>, junto con asimetrías azimutales más débiles <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>. Por esta razón, el ambiente de polvo del disco debe entenderse como dinámico y no como una estructura perfectamente axisimétrica.</p>
<p>Esta interpretación se refuerza con evidencia cinemática. Pinte et al.&nbsp;(2020) muestran que los candidatos a planetas se ubican dentro de una brecha y/o al final de una espiral detectada en el continuo de polvo <span class="citation" data-cites="pinte2020_dsharp">(<a href="#ref-pinte2020_dsharp" role="doc-biblioref">Pinte et al. 2020</a>)</span>. En otras palabras, las subestructuras de polvo no solo indican dónde se concentra o redistribuye el material sólido, sino que también coinciden espacialmente con posibles perturbadores embebidos.</p>
</section>
<section id="propiedades-del-polvo" class="level2">
<h2 class="anchored" data-anchor-id="propiedades-del-polvo">Propiedades del polvo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Propiedad</th>
<th>Valor</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Temperatura del polvo en anillos brillantes</td>
<td>B67: 24 K; B100: 15 K; B168: &gt;6 K</td>
<td>Temperatura del polvo, o límite inferior, estimada a partir de la intensidad del continuo en los principales anillos brillantes.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Profundidad óptica de extinción del polvo</td>
<td>B67: 0.64 ± 0.05; B100: 0.74 ± 0.05; B168: 0.1 ± 0.2</td>
<td>Extinción total del polvo en los anillos, incluyendo absorción y dispersión.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Profundidad óptica de dispersión del polvo</td>
<td>B67: ~0.1–0.2; B100: ~0.2–0.4</td>
<td>Contribución estimada de la dispersión del polvo en los principales anillos brillantes.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Extensión radial del continuo de polvo milimétrico</td>
<td>Dentro de 250 AU</td>
<td>Distancia máxima desde la estrella donde se detecta claramente la emisión de granos grandes en el continuo milimétrico.</td>
<td><span class="citation" data-cites="isella2016">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>)</span></td>
</tr>
<tr class="odd">
<td>Factor de depleción de polvo en los gaps</td>
<td>Gap interno: ~13 a &gt;100; gap medio: ~7 a 70; gap externo: ~3.6 a 6</td>
<td>Medida de cuánto disminuye la densidad de polvo dentro de cada brecha respecto de las regiones circundantes; valores mayores indican brechas más depletadas en polvo.</td>
<td><span class="citation" data-cites="isella2016">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="gas-en-el-disco" class="level2">
<h2 class="anchored" data-anchor-id="gas-en-el-disco">Gas en el disco</h2>
<p>En HD 163296, el disco gaseoso no termina donde se observa el continuo de polvo milimétrico. Al contrario, la emisión de CO se extiende mucho más allá del borde externo del polvo, alcanzando aproximadamente <strong>560 au</strong> desde la estrella central <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>Para interpretar la geometría del gas, es importante considerar que el CO no aparece como una sola capa. Las observaciones muestran dos superficies emisoras cálidas, correspondientes al lado frontal y al lado posterior del disco. Esta estructura produce una morfología característica que permite inferir la geometría vertical de las capas emisoras de CO <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>La emisión del lado posterior aparece más débil debido a una combinación de menor temperatura del gas emisor y absorción por material intermedio. La separación entre las capas frontal y posterior permite medir la geometría vertical de la superficie emisora de CO <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>La temperatura del gas trazado por CO disminuye con la distancia a la estrella: alcanza valores de hasta <strong>120 K</strong> en las regiones internas y baja hasta aproximadamente <strong>20 K</strong> en el borde externo del disco <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>En términos dinámicos, el movimiento global del gas está dominado por la gravedad estelar y se describe bien mediante rotación kepleriana alrededor de una estrella de aproximadamente <strong>2.0 M☉</strong> <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>A diferencia del polvo, el gas no muestra anillos y brechas tan marcados en los mapas de <span class="math inline">\(^{12}\)</span>CO, <span class="math inline">\(^{13}\)</span>CO y C<span class="math inline">\(^{18}\)</span>O J = 2−1. Sin embargo, estos trazadores sí muestran cambios en la pendiente del perfil radial de intensidad en posiciones asociadas con las brechas oscuras del continuo <span class="citation" data-cites="isella2016">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>)</span>. Esto indica que gas y polvo no se distribuyen de la misma manera.</p>
<p>En particular, la razón gas/polvo varía a través del disco y aumenta al menos por un factor de 5 dentro del gap interno de polvo, en comparación con regiones adyacentes <span class="citation" data-cites="isella2016">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>)</span>. Esto sugiere que en esa zona el polvo está más fuertemente depletado que el gas.</p>
</section>
<section id="propiedades-del-gas" class="level2">
<h2 class="anchored" data-anchor-id="propiedades-del-gas">Propiedades del gas</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Propiedad</th>
<th>Valor</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Extensión radial de la emisión de CO</td>
<td>~560 au</td>
<td>Distancia máxima desde la estrella donde el gas trazado por CO todavía se detecta claramente; muestra que el disco gaseoso se extiende mucho más que el continuo de polvo milimétrico.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Geometría de la capa emisora de CO</td>
<td>z<sub>CO</sub>(100 au) = 30 au; q = 0.5</td>
<td>Describe la altura de la superficie cálida emisora de CO sobre el plano medio del disco y cómo cambia con el radio; resume la estructura vertical observada del gas.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Rango de temperatura del gas trazado por CO</td>
<td>Disco interno: hasta 120 K; borde externo: hasta 20 K</td>
<td>Temperatura aproximada del gas detectado en CO desde las regiones internas hasta el disco externo; muestra que el gas es más caliente cerca de la estrella y más frío a radios mayores.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Perfil radial de temperatura del CO</td>
<td>T<sub>CO</sub>(K) ≈ 87 − 0.14 (r/au), entre 30 y 500 au</td>
<td>Relación empírica que describe cómo la temperatura del gas disminuye con la distancia a la estrella en una gran parte del disco.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Velocidad sistémica</td>
<td>5.8 km s<sup>−1</sup></td>
<td>Velocidad de referencia del sistema HD 163296 inferida a partir de observaciones de CO; se usa para describir el patrón global de rotación del disco.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="even">
<td>Cinemática del gas</td>
<td>Rotación kepleriana alrededor de una estrella de ~2.0 M☉</td>
<td>Comportamiento dinámico global del gas, consistente con un disco cuya rotación está gobernada principalmente por la gravedad de la estrella central.</td>
<td><span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span></td>
</tr>
<tr class="odd">
<td>Radio del disco gaseoso kepleriano</td>
<td>~550 AU</td>
<td>Tamaño aproximado del disco gaseoso que orbita la estrella; indica hasta dónde el gas forma parte de la estructura principal en rotación.</td>
<td><span class="citation" data-cites="isella2016">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Depleción de CO en las brechas</td>
<td>Gap interno: ΔCO1 = 0–2.5; gap medio: ΔCO2 = 3.5–70; gap externo: ΔCO3 = 1.8–6</td>
<td>Medida de cuánto disminuye el gas trazado por CO dentro de cada brecha; valores mayores indican una reducción más fuerte del gas en esa región.</td>
<td><span class="citation" data-cites="isella2016">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>)</span></td>
</tr>
<tr class="odd">
<td>Razón gas/polvo</td>
<td>~40 a 100 AU; &gt;1000 para r &gt; 250 AU; al menos 5 veces mayor dentro del gap interno</td>
<td>Razón entre material gaseoso y polvo en distintas zonas del disco; muestra que gas y polvo no se distribuyen de la misma manera y que algunas regiones están relativamente más depletadas en polvo que en gas.</td>
<td><span class="citation" data-cites="isella2016">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Relación de aspecto del gas</td>
<td>h = 0.05 a 60 AU; 0.065 a 100 AU; 0.07 a 160 AU</td>
<td>Razón entre el grosor del disco gaseoso y su radio; ayuda a describir qué tan verticalmente extendido o acampanado está el gas en distintas regiones.</td>
<td><span class="citation" data-cites="isella2016">(<a href="#ref-isella2016" role="doc-biblioref">Isella et al. 2016</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="evidencia-de-formación-planetaria" class="level2">
<h2 class="anchored" data-anchor-id="evidencia-de-formación-planetaria">Evidencia de formación planetaria</h2>
<p>La arquitectura de HD 163296, especialmente sus anillos y brechas, se asocia con perturbaciones reales en el gas del disco y no solo con cambios de opacidad del polvo. La detección de desviaciones respecto de la rotación kepleriana en las posiciones de anillos y brechas confirma que estas estructuras están relacionadas con variaciones en la presión del gas, es decir, con cambios en la densidad y/o temperatura del gas <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>En este contexto, la comparación entre observaciones y modelos de interacción planeta-disco sugiere que varias brechas podrían haber sido abiertas por planetas. Isella et al.&nbsp;(2018) indican que las brechas de densidad podrían explicarse mediante planetas con masas entre <strong>0.5 y 1 M_J</strong>, orbitando aproximadamente a <strong>48, 86 y 131 au</strong> de la estrella central <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>El mismo estudio también considera otro escenario: bajo condiciones de muy baja viscosidad, la estructura múltiple de anillos podría surgir por la interacción gravitacional con un único planeta de masa menor que Saturno, ubicado cerca de <strong>100 au</strong> <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>Además, subestructuras como el crescent observado dentro de D45 refuerzan esta interpretación. En discos de baja viscosidad, las interacciones planeta-disco pueden producir concentraciones asimétricas similares, especialmente si la masa planetaria supera aproximadamente <strong>0.1 M_J</strong> <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>Las asimetrías del continuo tampoco se interpretan como simples detalles morfológicos, sino como indicios de variaciones locales en la densidad de polvo. Estas variaciones apoyan la hipótesis de que la estructura compleja del disco de HD 163296 está siendo moldeada por interacción gravitacional con planetas todavía no observados directamente <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>Estudios dinámicos recientes extienden esta interpretación al proponer que HD 163296 podría albergar varios planetas gigantes en órbitas amplias, junto con un disco de planetesimales masivo <span class="citation" data-cites="polychroni2025">(<a href="#ref-polychroni2025" role="doc-biblioref">Polychroni et al. 2025</a>)</span>. En ese marco, la formación de planetas gigantes en el sistema puede excitar dinámicamente planetesimales y transportar material hacia regiones internas del disco <span class="citation" data-cites="polychroni2025">(<a href="#ref-polychroni2025" role="doc-biblioref">Polychroni et al. 2025</a>)</span>. Así, la evidencia de formación planetaria no se limita a la morfología observada, sino que también incluye sus posibles efectos sobre la redistribución de sólidos en el sistema.</p>
</section>
<section id="interpretación-física-de-hd-163296" class="level2">
<h2 class="anchored" data-anchor-id="interpretación-física-de-hd-163296">Interpretación física de HD 163296</h2>
<p>HD 163296 puede interpretarse físicamente como un disco donde el polvo no está distribuido de forma uniforme, sino que tiende a acumularse en regiones específicas del gas. En particular, los anillos <strong>B67</strong> y <strong>B100</strong> son estrechos en comparación con la altura de escala estimada del disco gaseoso, lo que se interpreta como evidencia de que el polvo migró radialmente y se concentró en máximos locales de presión <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>Esto significa que los anillos no son solo patrones visuales en la imagen, sino regiones donde el polvo se ha acumulado porque la presión local del gas favorece su concentración.</p>
<p>Al mismo tiempo, esta arquitectura se desarrolla dentro de un disco delgado y globalmente ordenado. La región externa no es perfectamente uniforme: presenta modulación significativa en la intensidad del anillo externo y asimetrías en la emisión de polvo <span class="citation" data-cites="diep2019 isella2018">(<a href="#ref-diep2019" role="doc-biblioref">Diep et al. 2019</a>; <a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>Esta complejidad no puede explicarse únicamente mediante atrapamiento suave de polvo. Las asimetrías observadas en el continuo apoyan la hipótesis de que la estructura compleja del disco es resultado de interacción gravitacional con planetas aún no detectados directamente <span class="citation" data-cites="isella2018">(<a href="#ref-isella2018" role="doc-biblioref">Isella et al. 2018</a>)</span>.</p>
<p>Mientras tanto, el gas conserva un movimiento global ordenado, dominado por rotación kepleriana <span class="citation" data-cites="diep2019">(<a href="#ref-diep2019" role="doc-biblioref">Diep et al. 2019</a>)</span>. En conjunto, estos resultados sugieren un sistema donde los anillos surgen por concentración de polvo en máximos de presión del gas, mientras que las estructuras más complejas, como asimetrías y modulaciones de brillo, apuntan a interacción activa entre el disco y posibles planetas en formación.</p>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">Referencias</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-benisty2010" class="csl-entry" role="listitem">
Benisty, M., A. Natta, A. Isella, et al. 2010. <span>“Strong Near-Infrared Emission in the Sub-AU Disk of the Herbig Ae Star HD 163296: Evidence of Refractory Dust?”</span> <em>Astronomy &amp; Astrophysics</em> 511: A74. <a href="https://doi.org/10.1051/0004-6361/200912898">https://doi.org/10.1051/0004-6361/200912898</a>.
</div>
<div id="ref-diep2019" class="csl-entry" role="listitem">
Diep, P. N., D. T. Hoai, N. B. Ngoc, et al. 2019. <span>“The Protoplanetary Disc HD 163296 as Observed by ALMA.”</span> <em>Vietnam Journal of Science, Technology and Engineering</em> 61 (2): 3–16. <a href="https://doi.org/10.31276/VJSTE.61(2).03-16">https://doi.org/10.31276/VJSTE.61(2).03-16</a>.
</div>
<div id="ref-isella2016" class="csl-entry" role="listitem">
Isella, Andrea, Greta Guidi, Leonardo Testi, et al. 2016. <span>“Ringed Structures of the HD 163296 Protoplanetary Disk Revealed by ALMA.”</span> <em>Physical Review Letters</em> 117 (25): 251101. <a href="https://doi.org/10.1103/PhysRevLett.117.251101">https://doi.org/10.1103/PhysRevLett.117.251101</a>.
</div>
<div id="ref-isella2018" class="csl-entry" role="listitem">
Isella, Andrea, Jane Huang, Sean M. Andrews, et al. 2018. <span>“The Disk Substructures at High Angular Resolution Project (DSHARP). IX. A High-Definition Study of the HD 163296 Planet-Forming Disk.”</span> <em>The Astrophysical Journal Letters</em> 869 (2): L49. <a href="https://doi.org/10.3847/2041-8213/aaf747">https://doi.org/10.3847/2041-8213/aaf747</a>.
</div>
<div id="ref-pinte2020_dsharp" class="csl-entry" role="listitem">
Pinte, Christophe, Daniel J. Price, François Ménard, et al. 2020. <span>“Nine Localized Deviations from Keplerian Rotation in the DSHARP Circumstellar Disks: Kinematic Evidence for Protoplanets Carving the Gaps.”</span> <em>The Astrophysical Journal Letters</em> 890: L9. <a href="https://doi.org/10.3847/2041-8213/ab6dda">https://doi.org/10.3847/2041-8213/ab6dda</a>.
</div>
<div id="ref-polychroni2025" class="csl-entry" role="listitem">
Polychroni, D., D. Turrini, S. Ivanovski, et al. 2025. <span>“HD 163296 and Its Giant Planets: Creation of Exo-Comets, Interstellar Objects and Transport of Volatile Material.”</span> <em>Astronomy &amp; Astrophysics</em> 697: A158. <a href="https://doi.org/10.1051/0004-6361/202453097">https://doi.org/10.1051/0004-6361/202453097</a>.
</div>
<div id="ref-rab2020" class="csl-entry" role="listitem">
Rab, Ch., I. Kamp, C. Dominik, et al. 2020. <span>“Interpreting High Spatial Resolution Line Observations of Planet-Forming Disks with Gaps and Rings: The Case of HD 163296.”</span> <em>Astronomy &amp; Astrophysics</em> 642: A165. <a href="https://doi.org/10.1051/0004-6361/202038712">https://doi.org/10.1051/0004-6361/202038712</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/martinaAbarca\.github\.io\/pilot-protoplanetary-disks-catalog\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>