<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>HL Tau: disco protoplanetario – Catálogo piloto de discos protoplanetarios</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-94b323657c735dfe3b1bf6ebb2c33a55.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Catálogo piloto de discos protoplanetarios</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./activity_morphology_es.html"> 
<span class="menu-text">Actividad morfológica</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./simulation.html"> 
<span class="menu-text">Simulación</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./investigaciones_publicaciones.html"> 
<span class="menu-text">Investigaciones y publicaciones</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./sobre_el_proyecto.html"> 
<span class="menu-text">Sobre el proyecto</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#nombres-del-objeto" id="toc-nombres-del-objeto" class="nav-link active" data-scroll-target="#nombres-del-objeto">Nombres del objeto</a></li>
  <li><a href="#ubicación" id="toc-ubicación" class="nav-link" data-scroll-target="#ubicación">Ubicación</a></li>
  <li><a href="#descripción-general-del-sistema" id="toc-descripción-general-del-sistema" class="nav-link" data-scroll-target="#descripción-general-del-sistema">Descripción general del sistema</a></li>
  <li><a href="#propiedades-generales-del-sistema" id="toc-propiedades-generales-del-sistema" class="nav-link" data-scroll-target="#propiedades-generales-del-sistema">Propiedades generales del sistema</a></li>
  <li><a href="#morfología-del-disco" id="toc-morfología-del-disco" class="nav-link" data-scroll-target="#morfología-del-disco">Morfología del disco</a></li>
  <li><a href="#mediciones-morfológicas" id="toc-mediciones-morfológicas" class="nav-link" data-scroll-target="#mediciones-morfológicas">Mediciones morfológicas</a></li>
  <li><a href="#polvo-en-el-disco" id="toc-polvo-en-el-disco" class="nav-link" data-scroll-target="#polvo-en-el-disco">Polvo en el disco</a></li>
  <li><a href="#propiedades-del-polvo" id="toc-propiedades-del-polvo" class="nav-link" data-scroll-target="#propiedades-del-polvo">Propiedades del polvo</a></li>
  <li><a href="#gas-en-el-disco" id="toc-gas-en-el-disco" class="nav-link" data-scroll-target="#gas-en-el-disco">Gas en el disco</a></li>
  <li><a href="#propiedades-del-gas" id="toc-propiedades-del-gas" class="nav-link" data-scroll-target="#propiedades-del-gas">Propiedades del gas</a></li>
  <li><a href="#evidencia-de-formación-planetaria" id="toc-evidencia-de-formación-planetaria" class="nav-link" data-scroll-target="#evidencia-de-formación-planetaria">Evidencia de formación planetaria</a></li>
  <li><a href="#interpretación-física" id="toc-interpretación-física" class="nav-link" data-scroll-target="#interpretación-física">Interpretación física</a></li>
  <li><a href="#referencias" id="toc-referencias" class="nav-link" data-scroll-target="#referencias">Referencias</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content column-page-left" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">HL Tau: disco protoplanetario</h1>
</div>



<div class="quarto-title-meta column-page-left">

    
  
    
  </div>
  


</header>


<div id="fig-hltau" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-hltau-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/hl_tau_eso.jpg" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Imagen anotada de ALMA del disco protoplanetario que rodea a la joven estrella HL Tau. La estructura de anillos y brechas visible en la emisión de polvo traza variaciones en la distribución del material sólido dentro del disco. Crédito de imagen: ALMA (ESO/NAOJ/NRAO)."><img src="images/hl_tau_eso.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img" width="650"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-hltau-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Imagen anotada de ALMA del disco protoplanetario que rodea a la joven estrella HL Tau. La estructura de anillos y brechas visible en la emisión de polvo traza variaciones en la distribución del material sólido dentro del disco. Crédito de imagen: ALMA (ESO/NAOJ/NRAO).
</figcaption>
</figure>
</div>
<p>Como se muestra en la <a href="#fig-hltau" class="quarto-xref">Figure&nbsp;1</a>, el disco de HL Tau presenta una secuencia de anillos brillantes y brechas oscuras en la emisión continua del polvo.</p>
<section id="nombres-del-objeto" class="level2">
<h2 class="anchored" data-anchor-id="nombres-del-objeto">Nombres del objeto</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Campo</th>
<th>Valor</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Nombre principal</td>
<td>HL Tau</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>Otras designaciones</td>
<td>Haro 6-14</td>
<td><span class="citation" data-cites="gomez1997">(<a href="#ref-gomez1997" role="doc-biblioref">Gomez et al. 1997</a>)</span></td>
</tr>
<tr class="odd">
<td>Ubicación</td>
<td>Nube molecular de Tauro</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="ubicación" class="level2">
<h2 class="anchored" data-anchor-id="ubicación">Ubicación</h2>
<p>HL Tau se encuentra en la nube molecular de Tauro, una región cercana de formación estelar que contiene numerosos objetos estelares jóvenes. Su distancia se suele adoptar como aproximadamente 140 pc, lo que permite que ALMA resuelva subestructuras del disco en escalas de solo unas pocas unidades astronómicas <span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span>.</p>
<p>Este entorno es importante para interpretar las observaciones. HL Tau es todavía un sistema muy joven, clasificado como una fuente T Tauri de Clase I–II, y permanece asociado con material molecular circundante. Por esta razón, las observaciones de líneas moleculares pueden incluir emisión tanto del disco como de la nube ambiente, por lo que el componente gaseoso debe interpretarse con cuidado <span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span>.</p>
</section>
<section id="descripción-general-del-sistema" class="level2">
<h2 class="anchored" data-anchor-id="descripción-general-del-sistema">Descripción general del sistema</h2>
<p>HL Tau es un sistema joven especialmente importante porque, aunque todavía se encuentra en una etapa temprana de evolución, ya posee un disco compacto y masivo junto con un flujo de salida altamente colimado. Esto indica que se trata de un sistema joven, pero dinámicamente activo. Las observaciones de ALMA revelaron una secuencia clara de anillos brillantes y brechas oscuras en el disco <span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span>, mostrando que una arquitectura compleja ya está presente en esta fase inicial.</p>
<p>Las regiones oscuras no están completamente vacías de emisión, lo que indica que el material sólido no desaparece por completo, sino que se redistribuye dentro del disco <span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span>. Sus propiedades son consistentes con crecimiento y evolución del polvo, por lo que estas brechas podrían estar relacionadas con etapas tempranas de formación planetaria.</p>
<p>Esta interpretación se refuerza al considerar que ALMA traza principalmente polvo de tamaño milimétrico. En presencia de protoplanetas embebidos, el polvo puede responder de forma distinta al gas: es más fácil producir brechas marcadas en el polvo que en el gas <span class="citation" data-cites="dipierro2015">(<a href="#ref-dipierro2015" role="doc-biblioref"><span class="nocase">Dipierro et al.</span> 2015</a>)</span>. En la misma línea, modelos de transferencia radiativa indican que las brechas principales están depletadas en polvo por al menos un factor de 10 y que el anillo más externo contiene menos granos milimétricos que las regiones internas <span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span>. Esto apunta a un crecimiento de granos más eficiente cerca de la estrella y/o a migración radial de granos grandes.</p>
<p>Además, el polvo milimétrico forma una capa geométricamente delgada, con una altura de escala cercana a 1 AU a 100 AU <span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span>. Esta estructura se interpreta como una señal clara de asentamiento vertical hacia el plano medio, precisamente la región donde el material sólido puede concentrarse y continuar evolucionando.</p>
</section>
<section id="propiedades-generales-del-sistema" class="level2">
<h2 class="anchored" data-anchor-id="propiedades-generales-del-sistema">Propiedades generales del sistema</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Propiedad</th>
<th>Valor</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Distancia</td>
<td>~140 pc</td>
<td>Distancia media adoptada para la región de HL Tau en Tauro.</td>
<td><span class="citation" data-cites="alma2015 pinte2016">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>; <a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Edad</td>
<td>≤1–2 Myr</td>
<td>Sistema joven, basado en la edad de la asociación de Tauro.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="odd">
<td>Clase evolutiva</td>
<td>Clase I–II</td>
<td>Fuente protoestelar en transición, con evidencia de envoltura y disco circunestelar.</td>
<td><span class="citation" data-cites="alma2015 pinte2016">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>; <a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Tipo espectral</td>
<td>K5</td>
<td>Clasificación espectral obtenida a partir de espectroscopía óptica de alta dispersión.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="odd">
<td>Masa estelar</td>
<td>~1.3–1.7 M☉</td>
<td>Estimada a partir de la cinemática del gas del disco, desde análisis de HCO+ hasta modelos de CO/HCO+ consistentes con rotación kepleriana.</td>
<td><span class="citation" data-cites="alma2015 pinte2016">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>; <a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Radio del disco</td>
<td>~120 AU</td>
<td>Radio externo aproximado del disco de polvo resuelto en longitudes de onda milimétricas.</td>
<td><span class="citation" data-cites="alma2015 pinte2016">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>; <a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="odd">
<td>Masa del disco</td>
<td>~0.03–0.14 M☉</td>
<td>Rango estimado a partir de modelos previos del continuo milimétrico citados en el estudio de ALMA.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>Inclinación del disco</td>
<td>~47°</td>
<td>Geometría del disco derivada mediante ajuste de elipses a la estructura de anillos resuelta.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="odd">
<td>Viscosidad del disco (α)</td>
<td>~3 × 10⁻⁴</td>
<td>Viscosidad turbulenta inferida a partir del grado de asentamiento del polvo necesario para reproducir el contraste observado entre anillos y brechas.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="morfología-del-disco" class="level2">
<h2 class="anchored" data-anchor-id="morfología-del-disco">Morfología del disco</h2>
<p>La morfología del disco de HL Tau está definida por una arquitectura anular muy pronunciada, resuelta por ALMA con un nivel de detalle sin precedentes a 2.9, 1.3 y 0.87 mm. Estas observaciones revelan un patrón de anillos brillantes y brechas oscuras presente en todas las longitudes de onda observadas, lo que muestra que se trata de subestructuras reales del disco y no de artefactos de imagen <span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span>.</p>
<p>En la imagen combinada a 1.0 mm, ALMA identifica siete pares de anillos brillantes y brechas oscuras, organizados como B1–B7 para los anillos y D1–D7 para las brechas <span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span>. Esta distribución revela una estructura radial compleja y altamente ordenada del material del disco.</p>
<p>Dipierro et al.&nbsp;(2015) describen a HL Tau como un sistema con brechas concéntricas y casi axisimétricas, destacando el carácter regular de su morfología. En su interpretación, esta apariencia puede entenderse porque ALMA observa principalmente polvo de tamaño milimétrico, y este componente no responde a los planetas embebidos de la misma forma que el gas. Como resultado, mientras el gas puede desarrollar estructuras espirales, el polvo tiende a resaltar anillos y brechas debido a la respuesta diferente entre gas y polvo <span class="citation" data-cites="dipierro2015">(<a href="#ref-dipierro2015" role="doc-biblioref"><span class="nocase">Dipierro et al.</span> 2015</a>)</span>.</p>
<p>En ese modelo, los planetas no se presentan como detecciones directas, sino como una prueba dinámica de plausibilidad. La morfología principal observada puede reproducirse con tres planetas embebidos ubicados aproximadamente a 13.2, 32.3 y 68.8 AU <span class="citation" data-cites="dipierro2015">(<a href="#ref-dipierro2015" role="doc-biblioref"><span class="nocase">Dipierro et al.</span> 2015</a>)</span>. Esto apoya la idea de que las brechas más prominentes podrían estar relacionadas con interacción planeta-disco.</p>
</section>
<section id="mediciones-morfológicas" class="level2">
<h2 class="anchored" data-anchor-id="mediciones-morfológicas">Mediciones morfológicas</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Estructura</th>
<th>Medición</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>D1</td>
<td>13.2 AU</td>
<td>Brecha oscura más interna identificada en el disco de HL Tau.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>B1</td>
<td>20.4 AU</td>
<td>Anillo brillante más interno identificado en el disco de HL Tau.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="odd">
<td>D2</td>
<td>32.3 AU</td>
<td>Brecha oscura en la estructura anular interna del disco.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>B2</td>
<td>38.1 AU</td>
<td>Anillo brillante en la estructura anular interna del disco.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="odd">
<td>D3</td>
<td>~42 AU</td>
<td>Brecha oscura intermedia en la estructura anular del disco.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>B3</td>
<td>~47 AU</td>
<td>Anillo brillante intermedio en la estructura anular del disco.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="odd">
<td>D4</td>
<td>~50 AU</td>
<td>Brecha oscura intermedia en la estructura anular del disco.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>B4</td>
<td>~55 AU</td>
<td>Anillo brillante intermedio en la estructura anular del disco.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="odd">
<td>D5</td>
<td>64.2 AU</td>
<td>Brecha oscura externa en la estructura anular del disco.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>B5</td>
<td>68.8 AU</td>
<td>Anillo brillante externo en la estructura anular del disco.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="odd">
<td>D6</td>
<td>73.7 AU</td>
<td>Brecha oscura externa en la estructura anular del disco.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>B6</td>
<td>81.3 AU</td>
<td>Anillo brillante externo en la estructura anular del disco.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="odd">
<td>D7</td>
<td>~91 AU</td>
<td>Brecha oscura más externa identificada en el disco de HL Tau.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>B7</td>
<td>~97 AU</td>
<td>Anillo brillante más externo identificado en el disco de HL Tau.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="polvo-en-el-disco" class="level2">
<h2 class="anchored" data-anchor-id="polvo-en-el-disco">Polvo en el disco</h2>
<p>En HL Tau, el polvo no está distribuido de forma homogénea, sino que presenta una estructura radial y vertical claramente diferenciada. Las observaciones de ALMA muestran un patrón de anillos brillantes y brechas oscuras en todas las longitudes de onda observadas. Además, las brechas no están completamente vacías de emisión <span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span>, lo que indica que el material sólido no desaparece por completo en esas regiones, sino que se redistribuye dentro del disco.</p>
<p>Pinte et al.&nbsp;(2016) muestran que el índice espectral aumenta desde las regiones internas hacia las externas, indicando que las propiedades de emisión del polvo cambian con el radio. En este contexto, la depleción de granos milimétricos en el anillo más externo se interpreta como evidencia de crecimiento de granos más rápido en las regiones centrales y/o migración radial de granos grandes hacia el interior <span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span>.</p>
<p>Las brechas principales muestran una reducción drástica en la densidad de polvo respecto de los anillos adyacentes. Esto indica que el material sólido no forma un disco suave, sino que ya está fuertemente concentrado en algunas regiones y depletado en otras.</p>
<p>Además, el polvo milimétrico está confinado a una capa geométricamente muy delgada, con una altura de escala cercana a 1 AU a 100 AU <span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span>. Esto constituye una señal clara de asentamiento vertical hacia el plano medio. En conjunto, esto sugiere que el continuo milimétrico está dominado por granos grandes y asentados, mientras que para reproducir la distribución espectral de energía se requiere una población adicional de granos submicrométricos distribuida en una estructura mucho más gruesa. Esto refuerza la idea de una fuerte estratificación del polvo en el disco.</p>
</section>
<section id="propiedades-del-polvo" class="level2">
<h2 class="anchored" data-anchor-id="propiedades-del-polvo">Propiedades del polvo</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Propiedad</th>
<th>Valor</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Perfil del índice espectral (0.87–2.9 mm)</td>
<td>~2.2 a ~3.5</td>
<td>El índice espectral aumenta desde el disco interno hacia el externo, indicando cambios radiales en la emisividad del polvo y/o en la profundidad óptica.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Distribución de polvo en el anillo más externo</td>
<td>Depletado en granos milimétricos</td>
<td>El anillo más externo muestra una falta relativa de granos grandes, consistente con menor eficiencia de crecimiento en esa región y/o migración radial de granos grandes hacia zonas internas.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="odd">
<td>Rango de masa de polvo en anillos</td>
<td>7–120 M⊕</td>
<td>Los anillos contienen una fracción importante del material sólido del disco.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Masa total de polvo</td>
<td>5 × 10^-4 M☉</td>
<td>Masa total de polvo del modelo de transferencia radiativa con mejor ajuste.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="odd">
<td>Altura de escala del polvo milimétrico</td>
<td>h1mm = 0.70 AU</td>
<td>Altura de escala del polvo de 1 mm en la capa asentada del disco.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Grosor del disco de polvo milimétrico a 100 AU</td>
<td>~1 AU; límite superior ≲ 2 AU</td>
<td>El disco emisor en continuo milimétrico es geométricamente muy delgado, consistente con fuerte asentamiento vertical.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="odd">
<td>Coeficiente de viscosidad turbulenta</td>
<td>α = 3 × 10^-4</td>
<td>Coeficiente de viscosidad turbulenta inferido a partir del modelo de asentamiento del polvo.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Razón gas/polvo en el plano medio a 100 AU</td>
<td>≈6</td>
<td>Razón gas/polvo estimada en el plano medio del disco a 100 AU para granos de hasta 3 mm.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="odd">
<td>Componente de polvo submicrométrico para la SED</td>
<td>h0 = 30 AU; masa de polvo = 2.8 × 10^-6 M☉</td>
<td>Se requiere un componente más grueso de granos pequeños para reproducir la distribución espectral de energía.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="gas-en-el-disco" class="level2">
<h2 class="anchored" data-anchor-id="gas-en-el-disco">Gas en el disco</h2>
<p>En HL Tau, el gas del disco no se observa como un componente simple y aislado, sino como parte de un sistema que todavía permanece embebido en un entorno activo. Las observaciones de ALMA muestran que su estudio se ve afectado por confusión espacial y cinemática producida por emisión extendida cercana a la velocidad ambiente de vlsr = 6–7 km s⁻¹ <span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span>. Esto significa que la señal del disco puede mezclarse parcialmente con la del material circundante.</p>
<p>Aun así, HCO+ permitió resolver espacialmente por primera vez la morfología del disco molecular de HL Tau <span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span>. Esta emisión revela una distribución de velocidades aproximadamente kepleriana en un rango detectable de 2.0 a 12.0 km s⁻¹.</p>
<p>De forma consistente, Pinte et al.&nbsp;(2016) muestran que tanto HCO+ como <sup>12</sup>CO presentan un componente espacialmente compacto y un gradiente de velocidad compatible con rotación de disco. Esto confirma que el gas más brillante está asociado con el disco y rota alrededor de la estrella.</p>
<p>No todos los trazadores describen esta dinámica de la misma manera. CN y HCN se detectan principalmente en absorción, y parte de la asimetría observada se interpreta como autoabsorción relacionada con el flujo de salida <span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span>. En conjunto, este panorama muestra que el gas en HL Tau sigue una rotación aproximadamente kepleriana, aunque su estructura y cinemática no son completamente simples.</p>
<p>Mientras que ALMA Partnership et al.&nbsp;(2015) deriva una masa estelar de aproximadamente 1.3 M☉, Pinte et al.&nbsp;(2016) concluyen que la cinemática del gas es más consistente con una estrella de ~1.7 M☉. Esto refuerza la idea de que HL Tau es un disco molecular joven y dinámico cuya interpretación detallada requiere modelamiento cuidadoso.</p>
</section>
<section id="propiedades-del-gas" class="level2">
<h2 class="anchored" data-anchor-id="propiedades-del-gas">Propiedades del gas</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Propiedad</th>
<th>Valor</th>
<th>Descripción</th>
<th>Fuente</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Trazadores moleculares</td>
<td>HCO⁺, ¹²CO, CN, HCN</td>
<td>Líneas moleculares detectadas hacia el sistema. En estos estudios, HCO⁺ y ¹²CO son los principales trazadores de la cinemática del disco, mientras que CN y HCN se detectan principalmente en absorción.</td>
<td><span class="citation" data-cites="alma2015 pinte2016">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>; <a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="even">
<td>Rango de velocidades</td>
<td>2–12 km/s</td>
<td>Rango detectable de velocidades radiales del gas en HCO⁺, consistente con un disco molecular en rotación.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="odd">
<td>Velocidad sistémica</td>
<td>7.0 ± 0.2 km/s</td>
<td>Velocidad sistémica adoptada para HL Tau, derivada de la absorción más profunda en CN y HCN.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>Tipo de rotación</td>
<td>Aproximadamente kepleriana</td>
<td>La cinemática del gas es consistente con rotación del disco alrededor de la estrella central, aunque el patrón observado está afectado por absorción y contaminación ambiental.</td>
<td><span class="citation" data-cites="alma2015 pinte2016">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>; <a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="odd">
<td>Inclinación del disco</td>
<td>~47°</td>
<td>Inclinación geométrica del disco usada para interpretar la cinemática del gas y estimar la masa estelar.</td>
<td><span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span></td>
</tr>
<tr class="even">
<td>Masa estelar cinemática</td>
<td>~1.3–1.7 M☉</td>
<td>La cinemática del gas implica una masa estelar dentro de este rango: las observaciones de ALMA dan ~1.3 M☉ a partir de HCO⁺ bajo una interpretación kepleriana simple, mientras que análisis posteriores favorecen ~1.7 M☉.</td>
<td><span class="citation" data-cites="alma2015 pinte2016">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>; <a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
<tr class="odd">
<td>Radio interno del gas</td>
<td>~10 AU (límite superior)</td>
<td>Radio interno aproximado del disco gaseoso inferido a partir de CO; se trata como límite superior porque está restringido por la sensibilidad a las velocidades más altas.</td>
<td><span class="citation" data-cites="pinte2016">(<a href="#ref-pinte2016" role="doc-biblioref"><span class="nocase">Pinte et al.</span> 2016</a>)</span></td>
</tr>
</tbody>
</table>
</section>
<section id="evidencia-de-formación-planetaria" class="level2">
<h2 class="anchored" data-anchor-id="evidencia-de-formación-planetaria">Evidencia de formación planetaria</h2>
<p>HL Tau entrega evidencia observacional de procesos relacionados con formación planetaria porque el material del disco ya está siendo esculpido dinámicamente. Las brechas observadas por ALMA no están completamente vacías, lo que indica que no corresponden a cavidades sin material, sino a regiones donde el polvo ha sido redistribuido por procesos físicos compatibles con interacción planeta-disco <span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span>.</p>
<p>Además, varios anillos muestran desplazamientos respecto del centro, y algunas subestructuras presentan proporciones resonantes, como <strong>D1:D2:D3:D4 = 1:4:6:8</strong>. Este tipo de organización radial puede interpretarse como una señal de procesos dinámicos capaces de abrir brechas, perturbar las órbitas del material del disco y ordenar la estructura radial.</p>
<p>Esta interpretación es apoyada por las simulaciones de Dipierro et al.&nbsp;(2015), donde se modelan tres planetas embebidos a <strong>13.2, 32.3 y 68.8 AU</strong>, con masas de <strong>0.2, 0.27 y 0.55 MJ</strong>. Ese escenario reproduce gran parte de las estructuras observadas en la imagen de ALMA <span class="citation" data-cites="dipierro2015">(<a href="#ref-dipierro2015" role="doc-biblioref"><span class="nocase">Dipierro et al.</span> 2015</a>)</span>.</p>
<p>En otras palabras, los planetas no se presentan aquí como objetos detectados directamente, sino como una explicación físicamente plausible de la arquitectura ordenada del disco. En este escenario, los protoplanetas abren brechas, empujan el polvo hacia los bordes de esas brechas y, debido a que el polvo responde de forma más visible que el gas, la imagen observada por ALMA adquiere naturalmente una morfología de anillos brillantes y brechas oscuras.</p>
</section>
<section id="interpretación-física" class="level2">
<h2 class="anchored" data-anchor-id="interpretación-física">Interpretación física</h2>
<p>HL Tau puede interpretarse físicamente como un sistema extremadamente joven que aún se encuentra en una etapa evolutiva activa, pero cuyo disco ya muestra una arquitectura compleja que difícilmente corresponde a una distribución pasiva de material. Las observaciones de ALMA lo presentan como un sistema que está emergiendo de su envoltura protoestelar, y aun en esta etapa ya muestra anillos brillantes, brechas oscuras, evidencia de crecimiento de granos y una organización radial que sugiere redistribución dinámica de gas y polvo <span class="citation" data-cites="alma2015">(<a href="#ref-alma2015" role="doc-biblioref"><span class="nocase">ALMA Partnership et al.</span> 2015</a>)</span>.</p>
<p>En este contexto, Dipierro et al.&nbsp;(2015) ofrecen una interpretación física más amplia: la morfología de HL Tau puede entenderse como el resultado de interacciones entre polvo, gas y planetas embebidos. El polvo milimétrico responde de forma más visible que el gas a las perturbaciones gravitacionales y, por eso, produce los anillos y brechas definidos que observa ALMA <span class="citation" data-cites="dipierro2015">(<a href="#ref-dipierro2015" role="doc-biblioref"><span class="nocase">Dipierro et al.</span> 2015</a>)</span>.</p>
<p>En conjunto, estos estudios convergen en una misma imagen: HL Tau no es simplemente un disco joven con subestructuras, sino un sistema en el que la evolución del polvo, la redistribución del material y la posible presencia de protoplanetas podrían estar esculpiendo activamente la arquitectura del disco.</p>
</section>
<section id="referencias" class="level2">
<h2 class="anchored" data-anchor-id="referencias">Referencias</h2>
<div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-alma2015" class="csl-entry" role="listitem">
<span class="nocase">ALMA Partnership, C. L. Brogan, L. M. Pérez, et al.</span> 2015. <span>“The 2014 ALMA Long Baseline Campaign: First Results from High Angular Resolution Observations Toward the HL Tau Region.”</span> <em>The Astrophysical Journal Letters</em> 808 (1): L3. <a href="https://doi.org/10.1088/2041-8205/808/1/L3">https://doi.org/10.1088/2041-8205/808/1/L3</a>.
</div>
<div id="ref-dipierro2015" class="csl-entry" role="listitem">
<span class="nocase">Dipierro, Giovanni, Giuseppe Lodato, Leonardo Testi, et al.</span> 2015. <span>“Planet–Disk Interactions in the HL Tau Disk.”</span> <em>Monthly Notices of the Royal Astronomical Society Letters</em> 453: L73–77. <a href="https://doi.org/10.1093/mnrasl/slv105">https://doi.org/10.1093/mnrasl/slv105</a>.
</div>
<div id="ref-gomez1997" class="csl-entry" role="listitem">
Gomez, Mercedes, Barbara A. Whitney, and Scott J. Kenyon. 1997. <span>“A Survey of Optical and Near-Infrared Jets in Taurus Embedded Sources.”</span> <em>The Astronomical Journal</em> 114 (3): 1138–53. <a href="https://doi.org/10.1086/118545">https://doi.org/10.1086/118545</a>.
</div>
<div id="ref-pinte2016" class="csl-entry" role="listitem">
<span class="nocase">Pinte, Christophe, François Ménard, Gaspard Duchêne, et al.</span> 2016. <span>“Dust and Gas in the Disk of HL Tau: Surface Density, Dust Settling, and Dust-to-Gas Ratio.”</span> <em>The Astrophysical Journal</em> 816 (1): 25. <a href="https://doi.org/10.3847/0004-637X/816/1/25">https://doi.org/10.3847/0004-637X/816/1/25</a>.
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/martinaAbarca\.github\.io\/pilot-protoplanetary-disks-catalog\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>